<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tony" failures="7" tests="30" name="Test" time="16.292" errors="0" timestamp="2024-12-01T15:36:48 IST">
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.NewTest" name="f" time="0.01"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.FirstTestNG" name="test1" time="0.0"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.FirstTestNG" name="test2" time="0.0"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.FirstTestNG" name="test3" time="0.001"/>
  <testcase classname="DependencyAttribute.Dependency" name="login" time="0.001"/>
  <testcase classname="DependencyAttribute.Dependency" name="logoutFromApplication" time="0.0"/>
  <testcase classname="DependencyAttribute.Dependency" name="closeApp" time="0.0"/>
  <testcase classname="Invocation.TestNGInvocationCount" name="test" time="0.0"/>
  <testcase classname="Invocation.TestNGInvocationCount" name="test" time="0.0"/>
  <testcase classname="Invocation.TestNGInvocationCount" name="test" time="0.001"/>
  <testcase classname="Invocation.TestNGInvocationCount" name="test" time="0.0"/>
  <testcase classname="Invocation.TestNGInvocationCount" name="test" time="0.002"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.AppTest" name="testApp" time="0.004"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.TestNGExamples2" name="loginToApplication" time="0.0"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.TestNGExamples2" name="makePayment" time="0.0"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.TestNGExamples2" name="collectReceipt" time="0.0"/>
  <testcase classname="LearnTestNGExamples.LearnTestNGExamples.TestNGExamples2" name="logoutFromApplication" time="0.0"/>
  <testcase classname="Assertion.SoftAssertionDemo" name="test1" time="0.004">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;12&amp;gt; but was:&amp;lt;13&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<12> but was:<13>
at Assertion.SoftAssertionDemo.test1(SoftAssertionDemo.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="TestNGWithSelenium.BeforeAndAfterAnnotation" name="loginToApplication" time="3.831"/>
  <testcase classname="TestNGWithSelenium.BeforeAndAfterAnnotation" name="verifyTitle" time="0.011"/>
  <testcase classname="TestNGWithSelenium.BeforeAndAfterAnnotation" name="verifyURL" time="0.037"/>
  <testcase classname="Assertion.AssertionInTestNG" name="test2" time="0.012">
    <failure type="java.lang.AssertionError" message="Validation Failed... expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: Validation Failed... expected [11] but found [10]
at Assertion.AssertionInTestNG.test2(AssertionInTestNG.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="Assertion.AssertionInTestNG" name="test3" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [Mahesh] but found [Mukesh]">
      <![CDATA[java.lang.AssertionError: expected [Mahesh] but found [Mukesh]
at Assertion.AssertionInTestNG.test3(AssertionInTestNG.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Assertion.AssertionInTestNG" name="test4" time="0.0">
    <failure type="java.lang.AssertionError" message="Validation Failed...: lists don&amp;apos;t have the same size expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: Validation Failed...: lists don't have the same size expected [3] but found [2]
at Assertion.AssertionInTestNG.test4(AssertionInTestNG.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="Assertion.AssertionInTestNG" name="test5" time="0.0">
    <failure type="java.lang.AssertionError" message="Validation Failed...: lists don&amp;apos;t have the same size expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: Validation Failed...: lists don't have the same size expected [3] but found [2]
at Assertion.AssertionInTestNG.test5(AssertionInTestNG.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="Assertion.AssertionInTestNG" name="test6" time="0.004">
    <failure type="java.lang.AssertionError" message="Validation Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Validation Failed expected [true] but found [false]
at Assertion.AssertionInTestNG.test6(AssertionInTestNG.java:97)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase classname="Assertion.AssertionInTestNG" name="test7" time="0.002">
    <failure type="java.lang.AssertionError" message="Validation Fail... expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Validation Fail... expected [false] but found [true]
at Assertion.AssertionInTestNG.test7(AssertionInTestNG.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test7 -->
  <testcase classname="Assertion.AssertionInTestNG" name="testingAssertionMethod" time="0.002"/>
  <testcase classname="Assignment.TestNG" name="methodFirst" time="0.006"/>
  <testcase classname="Assignment.TestNG" name="methodSecond" time="0.0"/>
</testsuite> <!-- Test -->
